### ISSUE TITLE
Use `bedrock.testInBrowser` in tests

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-angular-filters#1]
Use `bedrock.testInBrowser` in tests.

**Comment by mattcollier** [comment]
This test suite run using the bedrock.testInBrowser method take 6 seconds, vs 704ms using the method used in the master branch.

Can this be optimized somehow?

**Comment by dlongley** [comment]
> Can this be optimized somehow?

I think the main reason it's slower is because it reloads the whole page and test environment for each test file. Perhaps we could find a way to queue up tests inside the `testInBrowser` call so they'll all execute in a single environment.
